---
# File: main.yml
# Part: php-fpm
#
# Description: Enable php-fpm
#
# Parameters:
# - 
#
# Dependencies 
# 
#
# OS: Ubuntu


- block:
  - include: facts.yml
  - name: Install  packages
    apt: pkg={{ item }} state=present
    with_items:
      - "{{ php_fpm_pkg }}"
      #- libapache2-mod-fastcgi

  - name: enable module
    apache2_module: state=present name={{ item }}
    with_items:
      - actions
      - fastcgi
      - alias
    notify:
      - apache-restart

  tags: php-fpm
  become: yes
