---
# packages on armen
packages: 
  conky: conky-all
  musescore: musescore
  terminator: terminator
  language-pack-fr: language-pack-fr
  language-pack-gnome-fr: language-pack-gnome-fr
  python-pycurl: python-pycurl
  libpam-cracklib: libpam-cracklib
  audacity: audacity
  
#  pcbureau: [ conky terminator language-pack-fr language-pack-gnome-fr musescore]


