---
# file: iadetout.yml

- hosts: iadetout
  connection: local
  vars:
    bck_site: http://sql.free.fr/
    bck_site_dir: .
    bck_script: backup.php
    bck_login: iadetout
    bck_db: iadetout
    bck_mysql_host: localhost
    bck_ftp_site: ftpperso.free.fr
    bck_ftp_login: iadetout
    bck_target_dir: /home/franck/Documents/site/iadetout
    install_backup_script: no
    free: True

  roles:
    - mysqlbck
    - ftpbackup
