---
# file: kerbel.yml


- hosts: kerbel
  user: franck
  become: yes
  vars:
    hash_behaviour: merge
    default_runlevel: 2
    ssh_port: 22

  roles:
    - ansible-ohmyzsh
    - cryptomator
    - grafana
    - etckeeper
    - autosecupdate
    - aliases
    - nginx
    - redis
    - shm
    - packages
#    - numlockx
    - hosts
    - grub
    - checkrestart
    - guest
    - common
    - motd
    - sensors
    - sshd
#    - sshknownhosts
    - security
#    - compiz
    - inventory
    - users
    - nfs
    - usersettings
    - firewall
    - logwatch
    - collectd
#    - ipscan
    - bashrc
    - interface
    - wifi
    - noipv6
    - cron
#    - virtualbox
    - backintime
    - apache2
    - php-fpm
    - tls
    - mysql
    - glpi
    - fail2ban
#    - bootstrap
    - cgp
    - lynis
    - firefox
    - apache-sites
    - google_drive
    - eclipse
    
