---
# file: monanglais.yml

- hosts: monanglais
  connection: local
  vars:
    bck_site: http://sql.free.fr/
    bck_site_dir: .
    bck_script: backup.php
    bck_login: monanglais
    bck_db: monanglais
    bck_mysql_host: localhost
    bck_ftp_site: ftpperso.free.fr
    bck_ftp_login: monanglais
    bck_target_dir: /home/franck/Documents/site/monanglais
    install_backup_script: no
    free: True

  roles:
    - ftpbackup
    - mysqlbck
    
