---
# file: resasport.yml

- hosts: resasport
  connection: local
  vars:
    bck_site: http://sql.free.fr/
    bck_site_dir: .
    bck_script: backup.php
    bck_login: resasport
    bck_db: resasport
    bck_mysql_host: localhost
    bck_ftp_site: ftpperso.free.fr
    bck_ftp_login: resasport
    bck_target_dir: /home/franck/Documents/site/resasport
    install_backup_script: no
    free: True

  roles:
    - mysqlbck
    - ftpbackup
