---
# File: apache.yml
# Part: Apache
#
# Description: Enable an Apache server
#
# Parameters:
# - 
#
# Dependencies 
# 
#
# OS: Ubuntu


- block:

  - name: Install webserver packages
    apt: 
      pkg: 
        - php7.3
        - php7.3-common
        - libapache2-mod-php
        - php-mbstring
        - php-gettext
        - php-json
        - apache2
        - apache2-utils
        #- php-mcrypt
        - php-intl
        - php-mysql
        - php-xml
        #- awstats
      state: present
      force_apt_get: True

  - name: Set default listen port
    lineinfile: 
      dest: /etc/apache2/ports.conf
      create: yes
      state: present
      regexp: "^Listen"
      line: "Listen {{ apache_listen_port }}"

  - name: Enable modules
    apache2_module:
      state: "{{ item.state }}"
      name: "{{ item.name }}"
      ignore_configcheck: True
    with_items:
      - { name: 'php7.3' ,state: 'absent' }
      - { name: 'mpm_prefork' ,state: 'absent' }      
      - { name: 'mpm_event' ,state: 'absent' }      
      - { name: 'mpm_worker' ,state: 'present' }      
      - { name: 'userdir' ,state: 'present' }      
      - { name: 'headers' ,state: 'present' }
      - { name: 'rewrite' ,state: 'present' }
      - { name: 'expires' ,state: 'present' }
      - { name: 'ssl' ,state: 'present' }
      - { name: 'proxy_fcgi' ,state: 'present' }
      - { name: 'socache_shmcb' ,state: 'present' }
      - { name: 'http2' ,state: 'present' }

  - name : desactivate SSLv3
    lineinfile: 
      dest: /etc/apache2/mods-available/ssl.conf
      state: present
      regexp: "SSLProtocol"
      line: "        SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1"

  - name : desactivate unsecure cipher
    lineinfile: 
      dest: /etc/apache2/mods-available/ssl.conf
      state: present
      regexp: "SSLCipherSuite"
      line: "        SSLCipherSuite HIGH:!aNULL:!MD5:!3DES:!CAMELLIA:!AES128"

  - name : SSL server cipher order preference
    lineinfile: 
      dest: /etc/apache2/mods-available/ssl.conf
      state: present
      regexp: "SSLHonorCipherOrder"
      line: "        SSLHonorCipherOrder on"

  - name: Apache | Mask version
    replace: 
      dest: /etc/apache2/conf-available/security.conf
      regexp: '^ServerTokens (.*)'
      replace: 'ServerTokens ProductOnly'

  - name: Apache | Mask version
    replace: 
      dest: /etc/apache2/conf-available/security.conf
      regexp: '^ServerSignature (.*)'
      replace: 'ServerSignature Off'

  - name: Apache | anti-clickjacking X-Frame-Options header
    replace: 
      dest: /etc/apache2/conf-available/security.conf
      regexp: '(^|^#)Header set X-Frame-Options(.*)'
      replace: 'Header always append X-Frame-Options SAMEORIGIN'

  - name: Apache | 
    lineinfile: 
      dest: /etc/apache2/conf-available/security.conf
      state: present
      line: 'FileETag None'

  
  - name: Apache | 
    lineinfile: 
      dest: /etc/apache2/conf-available/security.conf
      state: present
      line: 'Header unset ETag'

  # Enable intl extension
  - name : Enable intl extension 
    lineinfile: 
      dest: "{{ item }}"
      state: absent
      regexp: "extension=intl"
      line: "extension=intl"
    with_items:
       - "/etc/php/{{ PHP_version }}/apache2/php.ini"
       - "/etc/php/{{ PHP_version }}/fpm/php.ini"
       - "/etc/php/{{ PHP_version }}/cli/php.ini"

  # Enable mbstring extension
  - name : Enable mbstring extension 
    lineinfile: 
      dest: "{{ item }}"
      state: absent
      regexp: "extension=mbstring"
      line: "extension=mbstring"
    with_items:
       - "/etc/php/{{ PHP_version }}/apache2/php.ini"
       - "/etc/php/{{ PHP_version }}/fpm/php.ini"
       - "/etc/php/{{ PHP_version }}/cli/php.ini"

  - name : Enable json extension 
    lineinfile: 
      dest: "{{ item }}"
      state: absent
      regexp: "extension=json"
      line: "extension=json"
    with_items:
       - "/etc/php/{{ PHP_version }}/apache2/php.ini"
       - "/etc/php/{{ PHP_version }}/fpm/php.ini"
       - "/etc/php/{{ PHP_version }}/cli/php.ini"

  - name : Enable pdo extension 
    lineinfile: 
      dest: "{{ item }}"
      state: absent
      regexp: "extension=pdo"
      line: "extension=pdo"
    with_items:
       - "/etc/php/{{ PHP_version }}/apache2/php.ini"
       - "/etc/php/{{ PHP_version }}/fpm/php.ini"
       - "/etc/php/{{ PHP_version }}/cli/php.ini"

  - name : Enable pdo_mysql extension 
    lineinfile: 
      dest: "{{ item }}"
      state: absent
      regexp: "extension=pdo_mysql"
      line: "extension=pdo_mysql"
    with_items:
       - "/etc/php/{{ PHP_version }}/apache2/php.ini"
       - "/etc/php/{{ PHP_version }}/fpm/php.ini"
       - "/etc/php/{{ PHP_version }}/cli/php.ini"

  - name : Enable mysqli extension 
    lineinfile: 
      dest: "{{ item }}"
      state: absent
      regexp: "extension=mysqli"
      line: "extension=mysqli"
    with_items:
       - "/etc/php/{{ PHP_version }}/apache2/php.ini"
       - "/etc/php/{{ PHP_version }}/fpm/php.ini"
       - "/etc/php/{{ PHP_version }}/cli/php.ini"




  # Set default timezone for php
  - name : Set default timezone for php
    lineinfile: 
      dest: "{{ item }}"
      state: present
      regexp: "date.timezone"
      line: 'date.timezone = "Europe/Paris"'
    with_items:
       - "/etc/php/{{ PHP_version }}/apache2/php.ini"
       - "/etc/php/{{ PHP_version }}/fpm/php.ini"
       - "/etc/php/{{ PHP_version }}/cli/php.ini"

  - name: Apache | Enable conf
    command: a2enconf security
    notify:
      - apache-restart

  tags: apache
  become: yes
  

- name: start apache2 service
  become: yes
  tags: apache
  service: 
    name: apache2 
    state: started 
    enabled: "{{ apache_enable }}"

- name: restart php-fpm service
  become: yes
  tags: apache
  service: 
    name: php7.3-fpm
    state: restarted 
    enabled: "{{ apache_enable }}"
