---
# telegraf for kerbel

mysql:
  user: telegraf
  password: 5VA1XtzvamSTSONA

# Must be defined with outputs_influxdb_https.conf plugin
telegraf_http:
  urls: https://influxk.pronostics.eu:8086
  insecure_skip_verify: 'false'

telegraf_plugins:
  - outputs_influxdb_http.conf
  - inputs_apache.conf
  - inputs_logparser.conf
#  - inputs_mysql.conf
#  - inputs_postfix.conf
  - inputs_redis.conf
  - inputs_system.conf
  - inputs_systemd_units.conf
  - inputs_phpfpm.conf
