#! /bin/sh
### BEGIN INIT INFO
# Provides:          backup-glpi
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     3
# Default-Stop:      0 1 6
# Short-Description: backup-glpi
# Description:       backup-glpi
### END INIT INFO

sh /home/franck/bin/backup-glpi.sh
