---
# File: role/firewall/main.yml
# Part:firewall
#
# Description: configure firewall rules
#
# Parameters:
# - 
#
# Dependencies 
# 
#
# OS: Ubuntu
- name: Install and configure ufw
  block:
  - name: Install ufw package
    apt: pkg={{ item }} state=present
    with_items:
       - ufw
  
  - name: fw | disable IPV6 in /etc/default/ufw
    lineinfile: dest=/etc/default/ufw
                  state=present
                  regexp="^IPV6="
                  line="IPV6=no"
  
  # reset firewall
  - name: fw | reset
    ufw: state=reset
  
  - name: fw | Allow ssh 
  #  ufw: rule=allow port=22 proto=tcp
    ufw: rule=allow port=22 proto=tcp src=10.35.0.0/24
  
  # Reject everything and enable UFW
  - name: fw | enable
    ufw: state=enabled policy=reject
  
  
  # Set logging
  - name: fw | set logging
    ufw: logging=off
  
  - name: fw | disable ipv6
    ufw: rule=reject proto=ipv6
  
  - name: fw | allow outgoing
    ufw: rule=allow interface=enp0s20 direction=out
  
  # Allow ssh
  - debug: msg="ssh on port  {{ ansible_ssh_port }}/tcp"
  
  - name: fw | Allow ssh 
  #  ufw: rule=allow port=22 proto=tcp
    ufw: rule=allow port={{ ansible_ssh_port }} proto=tcp src=10.35.0.0/24
  
  - name: Allow Linux Imaging and printing
    ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }} src={{ item.src }}
    with_items:
      - { rule: allow, port: 5353, proto: udp, src: 10.35.0.0/24 }
      - { rule: allow, port: 427 , proto: udp, src: 10.35.0.0/24 }
  
  # Manage hosts dependant rules
  - name: Manage hosts dependant rules
    ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }} src={{ item.src }}
    with_items:
      - "{{ ufw }}"
        
  - name: fw | deny incoming
    ufw: rule=reject direction=in
  
  - name: enable ufw and block everything else
    ufw: state=enabled policy=deny
  become: true
  tags: fw
  
