---

    - name: apache-restart
      become: yes
      service: name=apache2 state=restarted

    - name: apache-reload
      become: yes
      service: name=apache2 state=reloaded

    - name: php-fpm-restarted
      become: yes
      service: name="{{ php_fpm_service }}" state=restarted
