---
asites:
  dig:
    ServerName:		dig.pronostics.eu
    ServerIp:		_default_
    DocumentRoot:	/opt/applications/dig/WebContent
    ServerAdmin:	franck
    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu-0001/fullchain.pem
    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu-0001/privkey.pem
    SSLCertificateChainFile: /etc/letsencrypt/live/pronostics.eu-0001/chain.pem
    SpecificDirConf:       SpecificConf/authentication.conf
    SetHttpConf:	false
    ForceHttps:		true
    SSLVerifyClient: /admin
    phpfpm:		true		# use php-fpm if phpfmp is DEFINED

  phpmyadmin:
    ServerName:		mysql.pronostics.eu
    ServerIp:		_default_
    DocumentRoot:	/usr/share/phpmyadmin
    ServerAdmin:	franck
    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu-0001/fullchain.pem
    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu-0001/privkey.pem
    SSLCertificateChainFile: /etc/letsencrypt/live/pronostics.eu-0001/chain.pem
    SpecificConf:       SpecificConf/phpmyadmin.conf
    SetHttpConf:	false
    ForceHttps:		true
    SSLVerifyClient: /admin
    phpfpm:		true		# use php-fpm if phpfmp is DEFINED


  www.pronostics.eu:
    ServerName:		www.pronostics.eu
    ServerIp:		_default_
    DocumentRoot:	/opt/applications/prono4
    ServerAdmin:	franck
    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu-0001/fullchain.pem
    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu-0001/privkey.pem
    SSLCertificateChainFile: /etc/letsencrypt/live/pronostics.eu-0001/chain.pem
    SpecificConf:       SpecificConf/cakephp.conf    
    RedirectBlock:      SpecificConf/redirect.conf
    SetHttpConf:	false
    ForceHttps:		true
#    log:		/opt/applications/p35/logs # cakephp rotate file 10Mo
    phpfpm:		true		# use php-fpm if phpfmp is DEFINED
    pm_start_servers:   2     # Si non defini ici, utilisation de valeur par defaut du template
    pm_min_spare_servers: 1  # Si non defini ici, utilisation de valeur par defaut du template
    pm_max_spare_servers: 3   # Si non defini ici, utilisation de valeur par defaut du template

#-------------------------------------------------------
#
# pronostics cakephp v4
#
#-------------------------------------------------------
  www2.pronostics.eu:
    ServerName:		www2.pronostics.eu
    ServerIp:		_default_
    DocumentRoot:	/opt/applications/prono4
    ServerAdmin:	franck
    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu-0001/fullchain.pem
    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu-0001/privkey.pem
    SSLCertificateChainFile: /etc/letsencrypt/live/pronostics.eu-0001/chain.pem
    SpecificConf:       SpecificConf/cakephp.conf    
    RedirectBlock:      SpecificConf/redirect.conf
    SetHttpConf:	false
    ForceHttps:		true
#    log:		/opt/applications/p35/logs # cakephp rotate file 10Mo
    phpfpm:		true		# use php-fpm if phpfmp is DEFINED
    pm_start_servers:   2     # Si non defini ici, utilisation de valeur par defaut du template
    pm_min_spare_servers: 1  # Si non defini ici, utilisation de valeur par defaut du template
    pm_max_spare_servers: 3   # Si non defini ici, utilisation de valeur par defaut du template

  p35.pronostics.eu:
    ServerName:    p35.pronostics.eu
    ServerIp:    _default_
    DocumentRoot:  /opt/applications/prono4
    ServerAdmin: franck
    SSLCertificateFile:  /etc/letsencrypt/live/pronostics.eu-0001/fullchain.pem
    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu-0001/privkey.pem
    SSLCertificateChainFile: /etc/letsencrypt/live/pronostics.eu-0001/chain.pem
    SpecificConf:       SpecificConf/cakephp.conf    
    RedirectBlock:      SpecificConf/redirect.conf
    SetHttpConf:  false
    ForceHttps:    true
#    log:   /var/www/html/p35g/logs
    phpfpm:    true    # use php-fpm if phpfmp is DEFINED
    pm_start_servers:   2     # Si non defini ici, utilisation de valeur par defaut du template
    pm_min_spare_servers: 1  # Si non defini ici, utilisation de valeur par defaut du template
    pm_max_spare_servers: 3   # Si non defini ici, utilisation de valeur par defaut du template

  p5.pronostics.eu:
    ServerName:		p5.pronostics.eu
    ServerIp:		_default_
    DocumentRoot:	/opt/applications/p5
    ServerAdmin:	franck
    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu-0001/fullchain.pem
    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu-0001/privkey.pem
    SSLCertificateChainFile: /etc/letsencrypt/live/pronostics.eu-0001/chain.pem
    SpecificConf:       SpecificConf/cakephp.conf
    SetHttpConf:	false
    ForceHttps:		true
    log:		/opt/applications/p5/tmp/logs
    phpfpm:		true		# use php-fpm if phpfmp is DEFINED
    pm_start_servers:   2     # Si non defini ici, utilisation de valeur par defaut du template
    pm_min_spare_servers: 1  # Si non defini ici, utilisation de valeur par defaut du template
    pm_max_spare_servers: 3   # Si non defini ici, utilisation de valeur par defaut du template

  piwik:
    ServerName:		piwik.pronostics.eu
    ServerIp:		_default_
    DocumentRoot:	/opt/applications/matomo
    ServerAdmin:	franck
    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu-0001/fullchain.pem
    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu-0001/privkey.pem
    SSLCertificateChainFile: /etc/letsencrypt/live/pronostics.eu-0001/chain.pem
    SpecificConf:       SpecificConf/piwik.conf
    SetHttpConf:	false
    ForceHttps:		true
    phpfpm:		true		# use php-fpm if phpfmp is DEFINED
    pm_start_servers:   4     # Si non defini ici, utilisation de valeur par defaut du template
    pm_min_spare_servers: 4   # Si non defini ici, utilisation de valeur par defaut du template
    pm_max_spare_servers: 6   # Si non defini ici, utilisation de valeur par defaut du template


#
#
#  amp.p35.pronostics.eu:
#    ServerName:		amp.p35.pronostics.eu
#    ServerIp:		_default_
#    DocumentRoot:	/var/www/html/p35g
#    ServerAdmin:	franck
#    SSLCertificateFile:	/etc/letsencrypt/live/amp.p35.pronostics.eu/fullchain.pem
#    SSLCertificateKeyFile: /etc/letsencrypt/live/amp.p35.pronostics.eu/privkey.pem
##    SSLCertificateChainFile: /etc/letsencrypt/live/amp.p35.pronostics.eu/chain.pem
#    SpecificConf:       SpecificConf/cakephp.conf
##    SetHttpConf:	false
#    ForceHttps:		true
##    log:		/var/www/html/p35g/logs
##    phpfpm:		true		# use php-fpm if phpfmp is DEFINED
#    pm_start_servers:   2     # Si non defini ici, utilisation de valeur par defaut du template
#    pm_min_spare_servers: 1  # Si non defini ici, utilisation de valeur par defaut du template
#    pm_max_spare_servers: 2   # Si non defini ici, utilisation de valeur par defaut du template
#
#  amp.www.pronostics.eu:
#    ServerName:		amp.www.pronostics.eu
#    ServerIp:		_default_
#    DocumentRoot:	/var/www/html/p35g
#    ServerAdmin:	franck
#    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu/fullchain.pem
#    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu/privkey.pem
##    SSLCertificateChainFile: /etc/letsencrypt/live/amp.p35.pronostics.eu/chain.pem
#    SpecificConf:       SpecificConf/cakephp.conf
##    SetHttpConf:	false
#    ForceHttps:		true
##    log:		/var/www/html/p35g/logs
##    phpfpm:		true		# use php-fpm if phpfmp is DEFINED
#    pm_start_servers:   2     # Si non defini ici, utilisation de valeur par defaut du template
#    pm_min_spare_servers: 1  # Si non defini ici, utilisation de valeur par defaut du template
#    pm_max_spare_servers: 2   # Si non defini ici, utilisation de valeur par defaut du template
#
#  amp.pronostics.eu:
#    ServerName:		amp.pronostics.eu
#    ServerIp:		_default_
#    DocumentRoot:	/var/www/html/p35g
#    ServerAdmin:	franck
#    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu/fullchain.pem
#    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu/privkey.pem
##    SSLCertificateChainFile: /etc/letsencrypt/live/amp.p35.pronostics.eu/chain.pem
#    SpecificConf:       SpecificConf/cakephp.conf
##    SetHttpConf:	false
#    ForceHttps:		true
##    log:		/var/www/html/p35g/logs
##    phpfpm:		true		# use php-fpm if phpfmp is DEFINED
#    pm_start_servers:   2     # Si non defini ici, utilisation de valeur par defaut du template
#    pm_min_spare_servers: 1  # Si non defini ici, utilisation de valeur par defaut du template
#    pm_max_spare_servers: 2   # Si non defini ici, utilisation de valeur par defaut du template
#
#
#  redmine:
#    ServerName:		redmine.pronostics.eu
#    ServerIp:		_default_
#    DocumentRoot:	/usr/share/redmine/public
#    ServerAdmin:	franck
#    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu/fullchain.pem
#    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu/privkey.pem
##    SSLCertificateChainFile: /etc/letsencrypt/live/redmine.pronostics.eu/chain.pem
#    SpecificConf:       SpecificConf/redmine.conf
##    SetHttpConf:	false
#    ForceHttps:		true
##    phpfpm:		true		# use php-fpm if phpfmp is DEFINED
#
#  cgp:
#    ServerName:		cgp.pronostics.eu
#    ServerIp:		_default_
#    DocumentRoot:	/var/www/cgp
#    ServerAdmin:	franck
#    SSLCertificateFile:	/etc/letsencrypt/live/pronostics.eu/fullchain.pem
#    SSLCertificateKeyFile: /etc/letsencrypt/live/pronostics.eu/privkey.pem
##    SSLCertificateChainFile: /etc/letsencrypt/live/cgp.pronostics.eu/chain.pem
#    SpecificConf:       SpecificConf/cgp.conf
##    SetHttpConf:	false
#    ForceHttps:		true
##    phpfpm:		true		# use php-fpm if phpfmp is DEFINED
#
