---
# ufw specifics rules for vps-as

ufw:
  # Allow ssh
  - {rule: allow, 
     port: 2222, 
     proto: tcp,
     src: 0.0.0.0/0
    }
  # Allow web
  - {rule: allow, 
     port: 80, 
     proto: tcp,
     src: 0.0.0.0/0
    }
  - {rule: allow, 
     port: 443, 
     proto: tcp,
     src: 0.0.0.0/0
    }
