---
# file: roles/common/tasks/apport.yml
    
# Desactivate apport
  - name: Desactivate apport
    become: yes
    tags: apport
    lineinfile: dest=/etc/default/apport
                state=present
                regexp="enabled="
                line="enabled=0"
