---
# file: roles/hosts/tasks/sethosts.yml
    
# Update /etc/hosts file
#  - name: Setup | /etc/hosts
#    become: yes
#    copy: src=hosts dest=/etc/hosts owner=root group=root mode=644
#    tags: hosts

# Update /etc/hosts file
  - block:
    - name: Setup | /etc/hosts (linux)
      template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=644

    - name: Setup | add hostname in /etc/hosts
      lineinfile: dest=/etc/hosts
                state=present
                regexp="127.0.0.1"
                line="127.0.0.1 localhost {{ ansible_hostname }}"

    become: yes
    tags: hosts
    when: ansible_os_family == "Debian"


# Update /etc/hosts file
  - block:
    - name: Setup | c:\hosts (windows)
      win_template: src=hosts.j2 dest=C:\WINDOWS\system32\drivers\etc\hosts

    - name: Setup | add hostname in hosts file (windows)
      win_lineinfile: dest=C:\WINDOWS\system32\drivers\etc\hosts
                state=present
                regexp="127.0.0.1"
                line="127.0.0.1 localhost {{ ansible_hostname }}"

    tags: hosts
    when: ansible_os_family == "Windows"



