---
# file: roles/grub/tasks/main.yml
    
- name: grub | Disable quiet
  lineinfile: dest=/etc/default/grub
                state=present
                regexp="^GRUB_CMDLINE_LINUX_DEFAULT"
                line='GRUB_CMDLINE_LINUX_DEFAULT="nosplash"'
  tags: grub
  notify: grub-update
