---
# tasks file for cgp

- block:
  - name: install cgp from git repo
    git: repo=http://git.nethuis.nl/pub/cgp.git dest=/var/www/cgp

  - name: configure cgp
    copy: src=config.local.php dest=/var/www/cgp/conf/config.local.php owner=root group=root mode=0644

  - name: apache conf for cgp
    template: src=cgp.conf.j2 dest=/etc/apache2/sites-available/cgp.conf owner=root group=root mode=0644
 
  - name: a2ensite cgp
    command: a2ensite cgp
    notify:
      - reload apache2

  become: yes
  tags: cgp
